### ISSUE TITLE
Standardize labels

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/meta#2]
Rather than manually creating labels on each project, I'd really like to have these standardized (eg: `needs tests`, `glitch`, `bug`, etc) for all of pimutils.

[repo-utils/org-labels](repo-utils/org-labels) might help us maintain this (and copy labels to todoman, which currently only has one or two), though me need to make sure we actually standardize them on every repo first.

How does everyone feel about this?

cc @untitaker @geier (I think we should all `watch` this repo).

**Comment by geier** [comment]
sure, why not (watching now)

**Comment by untitaker** [comment]
I'm fine with it, but I would rather prefer an informal styleguide rather than enforcing total sync with a tool.

Currently vdirsyncer has multiple labels. For example, it has multiple ones starting with `mod: `, `type: `, `cat: `. I ripped that idea off from [Clap](https://github.com/kbknapp/clap-rs) and [Rust](https://github.com/rust-lang/rust). Perhaps start from there?

**Comment by untitaker** [comment]
FWIW it appears https://github.com/repo-utils/org-labels/pull/30 is needed to make org-labels run.

**Comment by skddc** [comment]
It's actually enough to manually edit the OAuth scope for the token created by the CLI auth, in one's user settings on GitHub. Needs to include "repo".

**Comment by WhyNotHugo** [comment]
I suggest closing this; labels have been working fine the way they are and I don't see as much value in standardising them any more.

**Comment by untitaker** [comment]
i feel the same way.
